---
- name: "GATHER DATA FROM NETBOX"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: http://172.16.66.124:8000
    netbox_token: 886ae40c1e5c26dab590a26ee065a60f9e650019
    validate_certs: no
  
  tasks:  
  - name: test
    debug:
      msg: "{{ netbox_url }}"