---
- name: "GATHER DATA FROM NETBOX"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: http://172.16.66.124:8000
    netbox_token: 886ae40c1e5c26dab590a26ee065a60f9e650019
    validate_certs: no
  
  tasks:  
  - name: test
    debug:
      msg: "{{ netbox_url }}"

  - name: "TASK 1: GET SITES WITH NB_QUERY"
    set_fact:
      sites: "{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint=netbox_url, token=netbox_token) }}"

  - name: "TASK 2: PRINT JUST THE SITE NAMES"
    debug:
      msg: "{{ sites | json_query('[*].value.name') }}"
  - name: "TASK 4: PRINT THE DEVICES"
    debug:
      msg: "{{ den_devices | json_query('[*].value.name') }}"