---
- name: "GATHER DATA FROM NETBOX"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: https://nb.suncloud.vn
    netbox_token: 71ecf6edf44b57d84ac56462f784577dab6912f0
    validate_certs: no
  
  tasks:
    - name: "TASK 1: GET SITES WITH NB_QUERY"
      set_fact:
        sites: "{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint=netbox_url, token=netbox_token,validate_certs=false) }}"

    - name: "TASK 2: PRINT JUST THE SITE NAMES"
      debug:
        msg: "{{ sites | json_query('[*].value.name') }}"